// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD63n6cxDaapQAewC6lnRN4YsQAGmPgNDs',
    appId: '1:607290187866:web:36a290fd959ca53eddb863',
    messagingSenderId: '607290187866',
    projectId: 'todolistapp-f6728',
    authDomain: 'todolistapp-f6728.firebaseapp.com',
    storageBucket: 'todolistapp-f6728.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwrU8Rc92qLMWecF3S_dHcdZ03A1QsFRw',
    appId: '1:607290187866:android:f9860505351d2c81ddb863',
    messagingSenderId: '607290187866',
    projectId: 'todolistapp-f6728',
    storageBucket: 'todolistapp-f6728.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSoRes09YaY2av-DVLd4jspuehhNQkM2s',
    appId: '1:607290187866:ios:f94b6e1ca37ea8e1ddb863',
    messagingSenderId: '607290187866',
    projectId: 'todolistapp-f6728',
    storageBucket: 'todolistapp-f6728.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSoRes09YaY2av-DVLd4jspuehhNQkM2s',
    appId: '1:607290187866:ios:f94b6e1ca37ea8e1ddb863',
    messagingSenderId: '607290187866',
    projectId: 'todolistapp-f6728',
    storageBucket: 'todolistapp-f6728.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD63n6cxDaapQAewC6lnRN4YsQAGmPgNDs',
    appId: '1:607290187866:web:38967a4b1a66beb0ddb863',
    messagingSenderId: '607290187866',
    projectId: 'todolistapp-f6728',
    authDomain: 'todolistapp-f6728.firebaseapp.com',
    storageBucket: 'todolistapp-f6728.appspot.com',
  );
}
